name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

 build-image-and-push:
    name: Build Docker image and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker compose build
        docker images
        
    - name: Tag Docker image
      run: |
        IMAGE_DATE=$(date +%Y-%m-%d-%H-%M-%S)
        docker image tag devops-node ${{ secrets.DOCKER_USERNAME }}/super-app-node:${IMAGE_DATE}
        docker image tag devops-php ${{ secrets.DOCKER_USERNAME }}/super-app-php:${IMAGE_DATE}

    - name: Push Docker image
      run: |
        docker image push --all-tags ${{ secrets.DOCKER_USERNAME }}/super-app-node
        docker image push --all-tags ${{ secrets.DOCKER_USERNAME }}/super-app-php
